version: '3.5'
services:
  mongo:
    image: mongo
    ports:
      - 27018:27017
    restart: always
    environment:
    # Copy these values from .env file
      MONGO_INITDB_ROOT_USERNAME:
      MONGO_INITDB_ROOT_PASSWORD:
      MONGO_INITDB_DATABASE:
      MONGO_DB_USER:
      MONGO_DB_PASSWORD:
    volumes:
      - './DBInit/createUser.sh:/docker-entrypoint-initdb.d/createUser.sh'
      - '~/payroll-production/data/db:/data/db'

  payroll-backend:
    depends_on:
      - "mongo"
    image: 'payroll-backend:production'
    build:
      context: .
      dockerfile: Dockerfile.prod
    restart: always
    ports:
      - '8888:8888'
    volumes:
      - '.env:/opt/app/.env'
